amdgpu: Patch out set_mst_en_for_sst
This breaks the build in -next due to issues with another tree:

/tmp/next/build/drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_debugfs.c: In function 'dp_force_sst_set':
/tmp/next/build/drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_debugfs.c:3248:20: error: 'struct dc_debug_options' has no member named 'set_mst_en_for_sst'
 3248 |  adev->dm.dc->debug.set_mst_en_for_sst = val;
      |                    ^
/tmp/next/build/drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_debugfs.c: In function 'dp_force_sst_get':
/tmp/next/build/drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_debugfs.c:3257:27: error: 'struct dc_debug_options' has no member named 'set_mst_en_for_sst'
 3257 |  *val = adev->dm.dc->debug.set_mst_en_for_sst;
      |

Signed-off-by: Mark Brown <broonie@kernel.org>