mm/memory-failure: remove stub function
This stub is no longer needed since the function is no longer
inside an #ifdef/#endif block.

Fixes this build error:

../mm/memory-failure.c:180:13: error: redefinition of `page_handle_poison'

Link: http://lkml.kernel.org/r/adb60490-484f-a154-e163-725e35a821dc@infradead.org
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Oscar Salvador <osalvador@suse.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>