mm-gup-pack-has_pinned-in-mmf_has_pinned-checkpatch-fixes
WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#25:
[peterx@redhat.com: fix build for task_mmu.c, introduce mm_set_has_pinned_flag, fix comments]

WARNING: please, no spaces at the start of a line
#130: FILE: mm/gup.c:1280:
+       if (!test_bit(MMF_HAS_PINNED, mm_flags))$

WARNING: suspect code indent for conditional statements (7, 15)
#130: FILE: mm/gup.c:1280:
+       if (!test_bit(MMF_HAS_PINNED, mm_flags))
+               set_bit(MMF_HAS_PINNED, mm_flags);

ERROR: code indent should use tabs where possible
#131: FILE: mm/gup.c:1281:
+               set_bit(MMF_HAS_PINNED, mm_flags);$

WARNING: please, no spaces at the start of a line
#131: FILE: mm/gup.c:1281:
+               set_bit(MMF_HAS_PINNED, mm_flags);$

total: 1 errors, 4 warnings, 90 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-gup-pack-has_pinned-in-mmf_has_pinned.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Peter Xu <peterx@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>